# Welcome to Jekyll!
#

# Site settings
title: Ben Fausch
description: |
  A web developer
owner: Ben Fausch
first_published: 2017
email: benjamin.fausch@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benfausch.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/benfauschdev>
  github: https://github.com/benfausch
  linkedin-square: https://linkedin.com/in/benfausch
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
